@startuml
'https://plantuml.com/sequence-diagram

class TodoListApplication {
+main(String[] args)
+start(Stage stage)
}

class Item {
-String itemDescription
-LocalDate itemDueDate
-boolean itemComplete
-int itemId
-{static}int count
-{static}incrementCount()
-initItemId()

+toString(): String
+getItemDescription(): String
+setItemDescription(String itemDescription)
+getItemDueDate(): LocalDate
+setItemDueDate(LocalDate itemDueDate)
+isItemComplete(): boolean
+setItemComplete(boolean itemComplete)
+getItemId(): int
+toggleItemComplete()
}

class ItemController {
-{final}ObservableList<Item> items
-ListView<Item> itemListView
-TextField descriptionText
-DatePicker dueDate
-Button addItemButton
-Button clearAllButton
-addItemToList(ActionEvent actionEvent)
-clearAll(ActionEvent actionEvent)
-deleteItemFromList(ActionEvent actionEvent)
-editItemList(ActionEvent actionEvent)
-markItemInList(ActionEvent actionEvent)
-showAllItems(ActionEvent actionEvent)
-showCompleteItems(ActionEvent actionEvent)
-showIncompleteItems(ActionEvent actionEvent)
-saveList(ActionEvent actionEvent)
-loadList(ActionEvent actionEvent)
-sortItemsList(ActionEvent actionEvent)
-disableDatePicker()

+addItem()
+validateDescriptionInput()
+checkForUnique()
+throwAlert(String errorType)
+refresh()
+sortItems()
+refreshList()
+clearItems()
+deleteItem(int itemId)
+editItem(int itemId)
+markItem(int itemId)
+showAll()
+showComplete()
+showIncomplete()
+saveItems()
+loadItems()
+verifyDate(String currentLine)
+disableDatePicker()
+verifyDate(String currentLine): LocalDate
+refreshList()
}

class Error {
-String headerText
-String contextText
+getHeaderText(): String
+getContentText(): String
}

file scene.fxml {
}

scene.fxml o-- ItemController
TodoListApplication o-- scene.fxml
ItemController o-- Item
ItemController o-- Error

@enduml